version: "3"

services:
  app:
    build:
      context: .
    ports:
      # host:container
      - "8000:3000"
    volumes:
      - ./app:/usr/src/app
      # create volume to cache node_modules
      - /usr/src/app/node_modules
    command: npm start
